apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-irsa-sa
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-enterprise-secrets
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: keycloak-enterprise-vault-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: enterprise/production/keycloak
        property: db_password
    - secretKey: ENTRA_CLIENT_SECRET
      remoteRef:
        key: enterprise/production/keycloak
        property: entra_client_secret
    - secretKey: AD_BIND_PASSWORD
      remoteRef:
        key: enterprise/production/keycloak
        property: ad_bind_password
    - secretKey: ARGOCD_CLIENT_SECRET
      remoteRef:
        key: enterprise/production/keycloak
        property: argocd_client_secret
    - secretKey: BACKSTAGE_CLIENT_SECRET
      remoteRef:
        key: enterprise/production/keycloak
        property: backstage_client_secret
