apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-cluster
  namespace: keycloak
  labels:
    app.kubernetes.io/name: vault
spec:
  serviceName: vault-internal
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
    spec:
      serviceAccountName: vault-sa
      containers:
        - name: vault
          image: hashicorp/vault:1.16.2
          args:
            - "server"
            - "-config=/vault/config/vault.hcl"
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          ports:
            - name: http
              containerPort: 8200
            - name: cluster
              containerPort: 8201
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
            - name: vault-data
              mountPath: /vault/data
  volumeClaimTemplates:
    - metadata:
        name: vault-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3-csi
        resources:
          requests:
            storage: 20Gi
